### ISSUE TITLE
Lacks specs

### ISSUE THREAD

**Issue by zph** [colinrymer/leftpad.ex#2]
How can I trust this repo when there are no tests to verify this mission critical behavior?

Also, will you pull this from HEX at some later point in time? Asking for a friend.

<3

**Comment by colinrymer** [comment]
It has doctests.

Also, I won't pull it until Phoenix and Ecto depend on it.

**Comment by colinrymer** [comment]
😁

**Comment by zph** [comment]
Property based testing with continuous integration is the only way you can be sure this will work!

You're putting the whole open source ecosystem in jeopardy!
